[Colors]
background=#121314
onBackground=#e3e2e2
surface=#121314
surfaceContainer=#1f2020
surfaceContainerHigh=#292a2b
onSurface=#e3e2e2
onSurfaceVariant=#c7c6c7
primary=#bac9d1
onPrimary=#253239
primaryContainer=#3b494f
onPrimaryContainer=#d6e5ed
secondary=#c0c8cc
onSecondary=#2a3235
secondaryContainer=#40484c
onSecondaryContainer=#dce4e9
tertiary=#b4cad5
onTertiary=#1e333c
tertiaryContainer=#354a53
onTertiaryContainer=#cfe6f2
error=#ffb4ab
shadow=#000000
outline=#919091
outlineVariant=#464747
layer0=#121314
layer1=#1b1c1c
onLayer1=#c7c6c7
subtext=#919091
