[General]
Background=Backgrounds/default.jpg
ColorsFile=colors.json
BlurRadius=100
BlurEnabled=true
BlurExtraZoom=1.1
BlurOverlayOpacity=0.3
ClockFontFamily=Google Sans Flex
ClockFontSize=90
ClockFontWeight=350
FontFamily=Google Sans Flex Medium
FontSize=15
Language=
# File plain-text con il path del wallpaper attivo (scritto da matugen).
# Default: ~/.local/state/quickshell/user/generated/wallpaper/path.txt
# Lascia vuoto per usare il default.
WallpaperPathFile=
